### ISSUE TITLE
Add a Pulsar sink task as well

### ISSUE THREAD

**Issue by aahmed-se** [riferrei/kafka-connect-pulsar#1]
Currently only a Pulsar source exists.

Support Kafka -> Pulsar workloads

**Comment by riferrei** [comment]
I haven't seen any interest yet in replicating data from Kafka to Pulsar using Kafka Connect. Since this is currently being addressed via the Pulsar I/O project; likely developers will leverage this framework to handle kafka -> pulsar replication.

Closing the issue for now.

-- @riferrei
